from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'rm.png'

BIG_FONT_SIZE = 40 
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 16

DEFAULT_TEXT_MARGIN = 15
MINIMUM_WIDTH = 500
